### ISSUE TITLE
FlutterKaigi CfP ドラフト

### ISSUE THREAD

**Issue by mafreud** [mafreud/patrol_sandbox#4]
## Patrol使用方法
developブランチではすでにPatrolのセットアップおよびIntegrationテストを書いてあります。以下手順で実行可能です。
1. ```dart pub global activate patrol_cli``` (patrol CLIが未インストールの場合)
2. ```patrol test --target integration_test/example_test.dart```

**Comment by mafreud** [comment]
## タイトル (70文字以内)
Patrolを使ってIntegrationテストを本番運用する。

## 概要 (600文字以内)
```
600文字以内で概要を記述してください。この情報は採択の基準となります。
記載される内容が具体的であるほど、採択の可能性が高まります。
記載されていることが望ましい観点:
- テーマの背景
- 予定している内容
- 対象となる聴講者層
```
みなさんはIntegrationテストを書いたことがありますか？多くの方がUnitテストやWidgetテストの経験はあるかもしれませんが、Integrationテストを実際に書き、運用した経験をお持ちの方は少ないのではないでしょうか。

FlutterのIntegrationテストは、時に煩雑であり、また、WebViewや通知ダイアログ等のネイティブが関与する場合には、これらネイティブ機能に対応できず失敗してしまいます。

そんな問題を解決するために、Patrolが開発されました。

Patrolは、LeanCode社が開発したFlutterアプリのテストのためのOSSフレームワークです。Patrolを使用すれば、DartでUIテストを簡単に書くことができます。さらに、Flutter公式パッケージでは対応が難しいネイティブサイドとの対応も可能です。また、Firebase Test Labを使用し、多数のデバイス上でE2Eテストを実行することもできます(Flutter未対応)。

このセッションでは、既存ソリューションの課題から始め、Patrolを活用したWidgetテストやIntegrationテストの実例を通じて、Patrolの機能とその有用性を解説します。Flutterプロジェクトのテスト自動化を進めたい方、また品質向上を目指す方にとって、このセッションは有益なものになるはずです。

## 想定視聴者
- Flutterプロジェクトの品質を高めたい方
- FlutterプロジェクトにE2Eテストを追加したい方
- integration_test に疲れた方
- Patrolについて詳しく知りたい方

**Comment by hukusuke1007** [comment]
LGTM!

**Comment by mafreud** [comment]
[@hukusuke1007 ](https://twitter.com/hobbydevelop/status/1692794181847241059?s=20)
